service: farmlist-api

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-west-2
  profile: farmlist

  environment:
    airtableSecretKey: ${env:AIRTABLE_SECRET_KEY}

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}

functions:
  list:
    # Defines an HTTP API endpoint that calls the main function in list.js
    handler: list.main
    events:
      - http:
          path: farms
          method: post
          cors: true
          authorizer: aws_iam


